pull_request_rules:
  - name: Automatic merge when new translations available
    conditions:
      - author=timeraa
      - title=New Crowdin translations
    actions:
      merge:
        method: merge
