pull_request_rules:
  - name: Automatic merge when the pull request has been approved.
    conditions:
      - base=master
      - "#approved-reviews-by>=2"
      - status-success=deepcode-ci-bot
    actions:
      merge:
        method: squash
  - name: Automatic merge when the pull request is made by SeMiD.
    conditions:
      - base=master
      - author=SeMiD
    actions:
      merge:
        method: squash
