files:
  - source: /en/Extension/*.json
    translation: /%two_letters_code%/Extension/%original_file_name%
  - source: /en/Website/*.json
    translation: /%two_letters_code%/Website/%original_file_name%
