files:
  - source: /Extension/*.json
    translation: /%locale_with_underscore%/Extension/%original_file_name%
  - source: /Website/*.json
    translation: /%locale_with_underscore%/Website/%original_file_name%
