files:
  - source: /en/Extension/*.json
    translation: /%locale_with_underscore%/Extension/%original_file_name%
  - source: /en/Website/*.json
    translation: /%locale_with_underscore%/Website/%original_file_name%
  - source: /en/Presence/*.json
    translation: /%locale_with_underscore%/Presence/%original_file_name%  
